### ISSUE TITLE
Add to Swift Package index

### ISSUE THREAD

**Issue by rizwankce** [icanzilb/MarkCodable#24]
I would love if `MarkCodable` got added to [swift package index ](https://swiftpackageindex.com). It's a great place for discovery.
We have all the things needed to get added except the GitHub release tag.

- [x] The package repositories must all be publicly accessible.
- [x] The packages must all contain a valid Package.swift file in the root folder.
- [x] The packages must be written in Swift 5.0 or later.
- [ ] The packages should have at least one release tagged as a [semantic version](https://semver.org/).
- [x] The packages must all output valid JSON when running swift package dump-package with the latest Swift toolchain.
- [x] The package URLs must include the protocol (usually https) and the .git extension.
- [x] The packages must all compile without errors.

I would like to take this up. If its okay!.

We also will get free DocC from SPI. [More info](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/)

**Comment by rizwankce** [comment]
@icanzilb I would need your help to make a tag on GitHub with semantic version. May be v1.0

**Comment by icanzilb** [comment]
Thank you — @rizwankce this is yours

I had a quick chat with Sven in the Swift Package Index Discord the other day and if I remember correctly he said that the semantic version isn't a hard requirement.

For now I'm still trying to figure out how `MarkCodable` would be versioned — you can read about the problem here https://github.com/icanzilb/MarkCodable/issues/15 so it might take a moment before this is settled.

Just fyi here's what it's been done so far for adding  to the SPI:
- https://github.com/SwiftPackageIndex/PackageList/issues/2715 - since we now support 5.6, I'd start by reopening this thread — maybe ping Sven there and ask how do re-submit since we're good with 5.6 which was the holdup before

**Comment by rizwankce** [comment]
Looks like its already added to SPI. Im gonna close the issue for now. May be follow up with DocC later

**Comment by icanzilb** [comment]
@rizwankce the current import is broken though because it was done when the package was only 5.7 or higher so the SPI metadata is broken:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/633862/188810226-4a95f21a-86f3-446e-b2b6-02d161ff94cc.png">

Would you like to ping them and verify how to reset the metadata and get the correct info up?

**Comment by rizwankce** [comment]
@icanzilb I just checked the details. New build are running automatically when we release a version or make some updates on the package.

**Comment by icanzilb** [comment]
Great, then let's see if the metadata shows up by tomorrow or so 👍🏼
